def get_rule_conditions_catalog():
    return {
        "combinators": ["all", "any", "not"],
        "uiHints": {
            "payload_path": {"widget": "json_path"},
            "payload_cmp.op": {"widget": "select", "options": ["eq", "gte", "lte", "between"]},
            "customer_cmp.op": {"widget": "select", "options": ["eq", "gte", "lte", "between"]},
            "customer_cmp.field": {
                "widget": "select",
                "options": [
                    "lifetime_points",
                    "status_points",
                    "created_at",
                    "last_activity_at",
                    "loyalty_status",
                    "status",
                ],
            },
            "customer_loyalty_status_in": {
                "widget": "remote_multi_select",
                "datasource": {
                    "endpoint": "/admin/ui-options/loyalty-tiers",
                    "method": "GET",
                    "valueField": "key",
                    "labelField": "name",
                    "brandVia": "X-Brand",
                },
            },
            "weekday_in": {
                "widget": "multi_select",
                "options": [
                    {"value": 0, "label": "Sunday"},
                    {"value": 1, "label": "Monday"},
                    {"value": 2, "label": "Tuesday"},
                    {"value": 3, "label": "Wednesday"},
                    {"value": 4, "label": "Thursday"},
                    {"value": 5, "label": "Friday"},
                    {"value": 6, "label": "Saturday"},
                ],
            },
            "customer_status_in": {
                "widget": "multi_select",
                "options": ["ACTIVE", "INACTIVE", "VIP", "BANNED"],
            },
        },
        "conditions": [
            {
                "type": "payload",
                "title": "Valeurs du payload (égalité)",
                "description": "Vérifie que certains champs du payload ont une valeur exacte (ex: amount == 100).",
                "params": {"<path>": "<expectedValue>"},
            },
            {
                "type": "payload_present",
                "title": "Champs payload présents",
                "description": "Vérifie que des champs existent dans le payload et ne sont pas vides.",
                "params": ["<path>"],
            },
            {
                "type": "payload_in",
                "title": "Valeur du payload dans une liste",
                "description": "Vérifie qu'un champ du payload est inclus dans une liste de valeurs autorisées.",
                "params": {"<path>": ["<value>"]},
            },
            {
                "type": "payload_contains",
                "title": "Payload contient une valeur",
                "description": "Vérifie qu'un champ du payload contient une valeur (texte ou liste).",
                "params": {"<path>": "<value>"},
            },
            {
                "type": "payload_cmp",
                "title": "Comparer une valeur du payload",
                "description": "Compare une valeur du payload (eq/gte/lte/between) avec une valeur donnée.",
                "params": {"path": "<path>", "op": "eq|gte|lte|between", "value": "any"},
            },
            {
                "type": "amount_gte",
                "title": "Montant minimum",
                "description": "Vérifie que payload.amount est supérieur ou égal à une valeur.",
                "params": "int",
            },
            {
                "type": "points_gte",
                "title": "Points minimum",
                "description": "Vérifie que payload.points est supérieur ou égal à une valeur.",
                "params": "int",
            },
            {
                "type": "customer_loyalty_status_in",
                "title": "Statut de fidélité (tiers)",
                "description": "Vérifie que le client est dans un ou plusieurs tiers de fidélité.",
                "params": ["<tierKey>"],
            },
            {
                "type": "customer_lifetime_points_gte",
                "title": "Points cumulés (lifetime) minimum",
                "description": "Vérifie que les points cumulés (historique) du client dépassent un seuil.",
                "params": "int",
            },
            {
                "type": "customer_status_in",
                "title": "Statut client",
                "description": "Vérifie que le statut du client est dans une liste (ACTIVE/VIP/etc.).",
                "params": ["<status>"],
            },
            {
                "type": "customer_created_days_gte",
                "title": "Ancienneté du compte (jours)",
                "description": "Vérifie que le client a été créé il y a au moins N jours.",
                "params": "int",
            },
            {
                "type": "customer_last_activity_days_gte",
                "title": "Inactivité (jours)",
                "description": "Vérifie que la dernière activité du client date d'au moins N jours.",
                "params": "int",
            },
            {
                "type": "customer_cmp",
                "title": "Comparer un champ client",
                "description": "Compare un champ du client (eq/gte/lte/between) avec une valeur.",
                "params": {"field": "<field>", "op": "eq|gte|lte|between", "value": "any"},
            },
            {
                "type": "weekday_in",
                "title": "Jour de la semaine",
                "description": "Vérifie que la date de l'événement tombe sur un ou plusieurs jours (0=dimanche..6=samedi).",
                "params": ["0..6"],
            },
            {
                "type": "first_purchase",
                "title": "Premier achat",
                "description": "Vérifie que c'est le premier achat du client.",
                "params": True,
            },
            {
                "type": "birthday",
                "title": "Anniversaire aujourd'hui",
                "description": "Vérifie que la date du jour correspond à l'anniversaire du client.",
                "params": True,
            },
            {
                "type": "birthday_bonus_points",
                "title": "Bonus anniversaire (points)",
                "description": "Condition spécifique anniversaire (valeur optionnelle selon votre logique métier).",
                "params": "int (optional)",
            },
            {
                "type": "earn_points_awarded_this_year",
                "title": "Points déjà gagnés cette année",
                "description": "Vérifie un total de points gagnés sur l'année en cours (selon votre implémentation).",
                "params": "int | {points:int}",
            },
            {
                "type": "bonus_awarded",
                "title": "Bonus déjà attribué",
                "description": "Vérifie qu'un bonus (bonusKey) a déjà été attribué au client.",
                "params": "str | {bonusKey:str}",
            },
        ],
    }
